name: Voyager CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-level: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run TypeScript Typecheck
      run: npx tsc --noEmit

    - name: Run Build Verify
      run: npm run build
